### ISSUE TITLE
关于requirements中audiocraft

### ISSUE THREAD

**Issue by zoe40404** [if-ai/ComfyUI_HunyuanVideoFoley#20]
git+https://github.com/facebookresearch/audiocraft.git#egg=audiocraft此项目必须要安装吗，我查看此项目需要torch版本降级为2.1.0，许多已安装的依赖包将出错，或者audiocraft有适配torch2.5.1版本的安装项目吗?

**Comment by rhystz** [comment]
it didn't install for me after running the requirements.txt without torch changes 😑 i basically never install custom nodes that change torch coz it takes ages and almost always breaks my comfy

**Comment by if-ai** [comment]
right I cahnged to use pypi should work now thanks for pointing this out

**Comment by anr2me** [comment]
i'm still getting an error when installing audiocraft with python 3.12.

according to this https://github.com/facebookresearch/audiocraft/issues/463#issuecomment-2260427025 audiocraft only works with python 3.9 😢
